# server port
server.port=10100
# redis
spring.data.redis.host=172.25.147.96
spring.data.redis.port=6379
spring.data.redis.database=4
spring.data.redis.password=bu2021!@
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true
feign.client.config.default.connectTimeout=30000
feign.client.config.default.readTimeout=30000
#log dir
log.dir=/home/appdeploy/logs/gj-web-api
### 自定义配置
supertar.swagger.api-url=testadmin.benefitunion.cn/bu-order-center
# eureka
eureka.client.serviceUrl.defaultZone=http://172.25.147.97:10010/gj-eureka/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=30
eureka.client.instance-info-replication-interval-seconds=30
eureka.client.eureka-server-connect-timeout-seconds=5
eureka.client.eureka-server-read-timeout-seconds=5

management.endpoint.shutdown.enabled=false
# cdn config
file.upload.type=tcloudCos
file.cos.domain=https://bufile-1257458953.cos.ap-beijing.myqcloud.com/
file.cdn.domain=http://static.gen-tech.cn/
# nas file config
tcloud.localFile.store.path=/mnt/file/test/busfile/
tcloud.localFile.store.path.template=/mnt/file/test/busfile/template/
tcloud.localFile.store.path.temporary=/mnt/file/test/busfile/temporary/
tcloud.localFile.store.path.upload=/mnt/file/test/busfile/upload/
tcloud.localFile.store.path.sync=/mnt/file/test/busfile/sync/
