### 测试环境
# 服务端口
server.port=10100
## redis单节点配置
spring.data.redis.host=172.21.0.13
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.password=benefitunion!@
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true
feign.client.config.default.connectTimeout=30000
feign.client.config.default.readTimeout=30000
#log dir
log.dir=/home/appdeploy/logs/gj-web-api
### 自定义配置
supertar.swagger.api-url=testadmin.benefitunion.cn/bu-order-center
# eureka
eureka.client.serviceUrl.defaultZone=http://172.21.0.2:10011/gj-eureka/eureka/
eureka.instance.prefer-ip-address=true
# 文件存储方式
file.upload.type=tcloudCos
file.cos.domain=https://bufile-1257458953.cos.ap-beijing.myqcloud.com/
file.cdn.domain=http://static.gen-tech.cn/
# 动态文件操作目录
tcloud.localFile.store.path=/mnt/file/test/busfile/
tcloud.localFile.store.path.template=/mnt/file/test/busfile/template/
tcloud.localFile.store.path.temporary=/mnt/file/test/busfile/temporary/
tcloud.localFile.store.path.upload=/mnt/file/test/busfile/upload/
tcloud.localFile.store.path.sync=/mnt/file/test/busfile/sync/
