spring.application.name=gj-web-api

# encoding default charset
server.servlet.encoding.charset=UTF-8
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=30MB

# ribbon default config
ribbon.ConnectTimeout=10000
ribbon.ReadTimeout=10000

# application version
application.version=@project.version@

spring.profiles.active=test

#log dir
log.dir=/home/appdeploy/logs/gj-web-api

