# server port
server.port=10010
# redis
spring.data.redis.host=172.25.147.96
spring.data.redis.port=6379
spring.data.redis.database=4
spring.data.redis.password=bu2021!@
#### database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://pgm-8vbc712f1w5l756i.pgsql.zhangbei.rds.aliyuncs.com:5432/uda
spring.datasource.username=uda
spring.datasource.password=uda2026!@
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# eureka
eureka.client.serviceUrl.defaultZone=http://172.25.147.97:10010/gj-eureka/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=30
eureka.client.instance-info-replication-interval-seconds=30
eureka.client.eureka-server-connect-timeout-seconds=5
eureka.client.eureka-server-read-timeout-seconds=5

# nas file config
localFile.store.path=/mnt/file/test/busfile/uda/
