### 生产环境
# 服务端口
server.port=10100

## redis单节点配置
spring.redis.host=172.19.0.14
spring.redis.port=26379
spring.redis.database=0
spring.redis.password=geREDIS2023!@

spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true

#log dir
log.dir=/home/appdeploy/logs/gj-web-api

# eureka
eureka.client.serviceUrl.defaultZone=http://172.19.0.14:10010/bu-eureka/eureka/

# 文件存储方式
file.upload.type=tcloudCos
file.cos.domain=https://bufile-1257458953.cos.ap-beijing.myqcloud.com/
file.cdn.domain=http://static.gentech.hk/

# 动态文件操作目录
tcloud.localFile.store.path=/mnt/file/test/busfile/